# Generated by Django 3.0.8 on 2020-07-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200720_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_favorite',
            new_name='is_verified',
        ),
    ]
